services:
  - type: web
    name: prezzi-sticker
    runtime: node
    plan: free
    buildCommand: npm install && npm run build && npx prisma migrate deploy
    startCommand: npm run start
    autoDeploy: true
    envVars:
      - key: NODE_VERSION
        value: 22.18.0
      - key: SHOPIFY_API_KEY
        sync: false
      - key: SHOPIFY_API_SECRET
        sync: false
      - key: SCOPES
        value: read_products,write_products,read_draft_orders,write_draft_orders
      - key: SHOPIFY_APP_URL
        sync: false
      - key: DATABASE_URL
        sync: false
      - key: DIRECT_URL
        sync: false
      - key: SHOPIFY_APP_SESSION_SECRET
        sync: false
